title: |
  <h1 style="font-family: Garamond, serif; color: #8d44a8; text-align: left;">
    Tulika Khargonkar
  </h1>


description: |
  <p style="color: #8d44a8; font-family: Arial, sans-serif;">
    A neuroscience graduate with a fancy for data and the stories it tells.
  </p>
  <br>
  
  ### Certifications

- [Google Data Analytics Specialisation](https://coursera.org/share/f4bd61035689a0b3ce9130d5ad94bb85)
- [Google AI Essentials](https://coursera.org/share/20d2cf89a545b24721052a056f61ac4d)
  
  <br>
  <a href="https://www.linkedin.com/in/tkhargonkar" 
     style="display: inline-block; background: #0073e6; color: white; padding: 10px 15px; border-radius: 5px; text-decoration: none; font-weight: bold;">
    View My LinkedIn Profile
  </a>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme


description: |

 



