title: Tulika Khargonkar

description: |
  <p style="color: #333; font-family: Arial, sans-serif;">
    A neuroscience graduate with a fancy for data and the stories it tells.
  </p>
  <br>
  <a href="https://www.linkedin.com/in/tkhargonkar" style="color: #0073e6; text-decoration: none; font-weight: bold;">
    View My LinkedIn Profile
  </a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

